# Generated by Django 2.2.14 on 2021-02-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
